# Generated by Django 3.0.3 on 2021-03-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='ok',
            field=models.CharField(default=14, max_length=100),
            preserve_default=False,
        ),
    ]
