# Generated by Django 3.0.3 on 2021-03-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210312_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(default=1, upload_to='photo/category/'),
            preserve_default=False,
        ),
    ]
