# Generated by Django 3.0.3 on 2021-03-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_customermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='image',
            field=models.ImageField(default=1, upload_to='user/'),
            preserve_default=False,
        ),
    ]
