# Generated by Django 3.0.3 on 2021-03-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_customermodel_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerModel',
            new_name='UserCreateModel',
        ),
    ]
