# Generated by Django 3.1.7 on 2021-04-03 10:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0011_auto_20210403_1003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cutomer',
            new_name='CustomerModel',
        ),
    ]
