# Generated by Django 3.1.7 on 2021-04-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20210403_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customermodel',
            name='mobile',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
